name: wechat robot push
on:
  push:
    branches:
      - dev
  schedule:
    - cron: '28 16 * * *'
    - cron: '29 16 * * *'
jobs:
  good-morning:
    runs-on: ubuntu-latest
    steps:
    - name: 企业微信markdown消息发送
      uses: fifsky/wechat-work-action@master
      with:
        url: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=ff58a9f4-b903-45da-baaa-4519fabe812f
        type: markdown
        content: |
          # Tips
          ## Hello
          > from github action message
          > ^_^
          - repository: 11
          - committer: 22
          - compare: 33
          - job status: 44
