name: wechat robot push
on:
  push:
    branches:
      - dev
jobs:
  good-morning:
    runs-on: ubuntu-latest
    steps:
    - name: 企业微信markdown消息发送
      uses: fifsky/wechat-work-action@master
      with:
        url: ff58a9f4-b903-45da-baaa-4519fabe812f
        type: markdown
        content: |
          # Tips
          ## Hello
          > from github action message
          > ^_^
          - repository: ${{ github.repository }}
          - committer: ${{ github.actor }}
          - compare: [view](${{ github.event.compare }})
          - job status: ${{ job.status }}
