name: wechat robot push
on:
  push:
  schedule:
    - cron: '0 1 * * *'
    - cron: '59 0 * * *'
jobs:
  good-morning:
    runs-on: ubuntu-latest
    steps:
    - name: 企业微信markdown消息发送
      uses: fifsky/wechat-work-action@master
      with:
        url: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=ff58a9f4-b903-45da-baaa-4519fabe812f
        type: markdown
        content: |
          # 美好的一天
          ## 开始摸鱼啦
